/** Spell, patronus, wand wood & core manifests (Harry Potter + Hogwarts Legacy). */

export const HOUSES = {
  gryffindor: { label: "Gryffindor", blurb: "Nerve, daring, and a heart that leads from the front." },
  slytherin: { label: "Slytherin", blurb: "Ambition, cunning, and the will to shape your fate." },
  ravenclaw: { label: "Ravenclaw", blurb: "Wit, curiosity, and love of a beautiful idea." },
  hufflepuff: { label: "Hufflepuff", blurb: "Loyalty, patience, and quiet, stubborn decency." },
};

export const CLASSES = {
  class_dada: { label: "Defence Against the Dark Arts", blurb: "You want your wand hand steady when it counts." },
  class_charms: { label: "Charms", blurb: "Small precise magic — clever solutions in every flick." },
  class_transfiguration: { label: "Transfiguration", blurb: "You love when one thing becomes another, perfectly." },
  class_herbology: { label: "Herbology", blurb: "Growth, care, and the patience of greenhouses." },
  class_potions: { label: "Potions", blurb: "Measured steps, subtle transformations, quiet mastery." },
  class_divination: { label: "Divination", blurb: "Meaning in patterns — or the courage to believe in them." },
  class_care_of_magical_creatures: { label: "Care of Magical Creatures", blurb: "Trust earned talon by talon, feather by feather." },
  class_astronomy: { label: "Astronomy", blurb: "Perspective from the tower — distant light, patient math." },
};

/** Every playable / named spell in Hogwarts Legacy plus major Harry Potter spells. */
export const SPELLS = {
  spell_basic_cast: { label: "Basic Cast", blurb: "Your foundation is simple, reliable strikes — the duelist’s heartbeat." },
  spell_revelio: { label: "Revelio", blurb: "You cannot resist unveiling what is hidden — truth as compulsion." },
  spell_protego: { label: "Protego", blurb: "A shield first: timing, poise, and perfect boundaries." },
  spell_stupefy: { label: "Stupefy", blurb: "End the fight cleanly — force without relish." },
  spell_ancient_magic_throw: { label: "Ancient Magic Throw", blurb: "You turn the battlefield itself into a weapon." },
  spell_ancient_magic: { label: "Ancient Magic", blurb: "Rare, overwhelming bursts — power you do not explain." },
  spell_levioso: { label: "Levioso", blurb: "Control through lift — enemies hang on your decision." },
  spell_transformation: { label: "Transformation", blurb: "You reshape what something is, not merely where it stands." },
  spell_glacius: { label: "Glacius", blurb: "Cold precision — you slow the world until it obeys." },
  spell_arresto_momentum: { label: "Arresto Momentum", blurb: "A single frozen instant, chosen by you." },
  spell_incendio: { label: "Incendio", blurb: "Heat, courage, and the honesty of open flame." },
  spell_expelliarmus: { label: "Expelliarmus", blurb: "Disarm, do not destroy — a signature of restraint." },
  spell_confringo: { label: "Confringo", blurb: "Blasts that crack shields — loud, decisive, final." },
  spell_bombarda: { label: "Bombarda", blurb: "You solve problems with spectacular force." },
  spell_diffindo: { label: "Diffindo", blurb: "Clean cuts — surgical, surgical, and mercilessly neat." },
  spell_depulso: { label: "Depulso", blurb: "Distance is safety; you shove threats away." },
  spell_descendo: { label: "Descendo", blurb: "Gravity as verdict — what rises must fall, hard." },
  spell_flipendo: { label: "Flipendo", blurb: "Chaos with a grin — you love a dramatic knockback." },
  spell_lumos: { label: "Lumos", blurb: "Light where others panic in the dark." },
  spell_reparo: { label: "Reparo", blurb: "You mend what breaks — objects, plans, and people." },
  spell_alohomora: { label: "Alohomora", blurb: "Locks are suggestions; curiosity is law." },
  spell_disillusionment: { label: "Disillusionment", blurb: "You move unseen until the perfect moment." },
  spell_wingardium_leviosa: { label: "Wingardium Leviosa", blurb: "Classic, graceful lift — precision over swagger." },
  spell_evanesco: { label: "Evanesco", blurb: "Vanishing trouble — tidy endings." },
  spell_accio: { label: "Accio", blurb: "What you need comes to your hand — irresistible pull." },
  spell_petrificus_totalus: { label: "Petrificus Totalus", blurb: "Total stillness — control without a scream." },
  spell_conjuring_spell: { label: "Conjuring Spell", blurb: "Creation from nothing — your imagination made solid." },
  spell_altering_spell: { label: "Altering Spell", blurb: "You tweak reality’s furniture until it fits your vision." },
  spell_expecto_patronum: { label: "Expecto Patronum", blurb: "Hope weaponised — memory as a guardian." },
  spell_reducto: { label: "Reducto", blurb: "Shatter obstacles; subtlety is for another day." },
  spell_sectumsempra: { label: "Sectumsempra", blurb: "Hidden cuts — dangerous knowledge you might not admit loving." },
  spell_obliviate: { label: "Obliviate", blurb: "You would erase pain — or evidence — to reshape a story." },
  spell_riddikulus: { label: "Riddikulus", blurb: "Laughter as armour — you mock fear until it shrinks." },
  spell_confundo: { label: "Confundo", blurb: "A wandering mind — yours or theirs — becomes your tool." },
  spell_silencio: { label: "Silencio", blurb: "Quiet authority; some voices should simply stop." },
  spell_aguamenti: { label: "Aguamenti", blurb: "Clean water, clean conscience — or a tide when needed." },
  spell_episkey: { label: "Episkey", blurb: "Small stitches for wounds — kindness with a wand." },
  spell_expulso: { label: "Expulso", blurb: "Concussive push — you clear space the hard way." },
  spell_piertotum_locomotor: { label: "Piertotum Locomotor", blurb: "You wake stone and steel to defend what matters." },
  spell_avada_kedavra: { label: "Avada Kedavra", blurb: "The final word — you accept there is no coming back." },
  spell_crucio: { label: "Crucio", blurb: "Pain as leverage — you mean to be remembered." },
  spell_imperio: { label: "Imperio", blurb: "Another’s will, yours to steer — control absolute." },
};

/** Corporeal forms named in HP media, Pottermore-style lists, Hogwarts Mystery & Legacy. */
export const PATRONUSES = {
  patronus_stag: { label: "Stag", blurb: "Proud, protective, galloping straight at what frightens you." },
  patronus_doe: { label: "Doe", blurb: "Gentle, watchful love — a guide through the coldest wood." },
  patronus_otter: { label: "Otter", blurb: "Playful resilience — joy that refuses to drown." },
  patronus_hare: { label: "Hare", blurb: "Quick, bright-eyed, a little strange — and honest about it." },
  patronus_jack_russell_terrier: { label: "Jack Russell Terrier", blurb: "Scrappy loyalty; you worry at problems until they yield." },
  patronus_weasel: { label: "Weasel", blurb: "Clever, busy, underestimated — until the bite lands." },
  patronus_lynx: { label: "Lynx", blurb: "Regal warnings — you see the trap before others smell it." },
  patronus_phoenix: { label: "Phoenix", blurb: "Rare rebirth — endings that become beginnings." },
  patronus_goat: { label: "Goat", blurb: "Stubborn kindness; you climb where others refuse the path." },
  patronus_cat: { label: "Cat", blurb: "Precise independence — affection on your own terms." },
  patronus_persian_cat: { label: "Persian cat", blurb: "Composed, ornamental power — softness hiding steel." },
  patronus_black_cat: { label: "Black cat", blurb: "Luck you make for yourself — shadows as company." },
  patronus_mouse: { label: "Mouse", blurb: "Small does not mean weak — nimble hope in tight places." },
  patronus_wolf: { label: "Wolf", blurb: "Pack, moonlight, and teeth for what threatens your own." },
  patronus_jack_rabbit: { label: "Jack rabbit", blurb: "Bursts of speed — courage that looks like flight." },
  patronus_swan: { label: "Swan", blurb: "Grace with an edge — beauty that will peck if cornered." },
  patronus_white_swan: { label: "White swan", blurb: "Memory made visible — elegy turned shield." },
  patronus_fox: { label: "Fox", blurb: "Wit, rust-red courage, and escape routes planned ahead." },
  patronus_boar: { label: "Boar", blurb: "Shoulder-first bravery — you charge the brush without flinching." },
  patronus_magpie: { label: "Magpie", blurb: "Bright curiosity — what shines might be yours to protect." },
  patronus_horse: { label: "Horse", blurb: "Open-field nerve — strength that likes to run." },
  patronus_white_stallion: { label: "White stallion", blurb: "Legendary stride — hope with a mane of light." },
  patronus_unicorn: { label: "Unicorn", blurb: "Almost impossibly rare — purity of intent, fierce if betrayed." },
  patronus_abraxan: { label: "Abraxan winged horse", blurb: "Power that needs taming — grandeur with muscle." },
  patronus_tiger: { label: "Tiger", blurb: "Striped certainty — patience, then explosion." },
  patronus_cheetah: { label: "Cheetah", blurb: "Speed as philosophy — strike before doubt arrives." },
  patronus_leopard: { label: "Leopard", blurb: "Quiet ambush — you prefer the high branch." },
  patronus_spotted_hare: { label: "Spotted hare", blurb: "Field-light cleverness — zigzags through danger." },
  patronus_mountain_hare: { label: "Mountain hare", blurb: "Cold heights suit you; you thrive where air is thin." },
  patronus_lop_eared_rabbit: { label: "Lop-eared rabbit", blurb: "Soft ears, stubborn heart — comfort as courage." },
  patronus_rabbit: { label: "Rabbit", blurb: "Quick hope — small footprints, large circles." },
  patronus_hummingbird: { label: "Hummingbird", blurb: "Impossible energy — joy that hovers and darts." },
  patronus_mink: { label: "Mink", blurb: "Sleek, fierce polish — elegance with teeth." },
  patronus_rhinoceros: { label: "Rhinoceros", blurb: "Armoured momentum — you do not dodge, you endure." },
  patronus_crocodile: { label: "Crocodile", blurb: "Patient water — still until the decisive snap." },
  patronus_pug: { label: "Pug", blurb: "Snorted loyalty — comedy and courage in one wrinkled face." },
  patronus_polar_bear: { label: "Polar bear", blurb: "Ice-breath strength — warmth saved for your chosen few." },
  patronus_hedgehog: { label: "Hedgehog", blurb: "Soft centre, prickly perimeter — boundaries are kindness." },
  patronus_raven: { label: "Raven", blurb: "Omen-wit — you read patterns in the black feathers." },
  patronus_crow: { label: "Crow", blurb: "Clever scavenger of truth — nothing wasted, nothing forgotten." },
  patronus_eagle: { label: "Eagle", blurb: "Soaring perspective — sharp and honest from above." },
  patronus_lioness: { label: "Lioness", blurb: "Protective thunder — the pride walks because you do." },
  patronus_ladybird: { label: "Ladybird", blurb: "Tiny, bright, surprisingly mighty — luck with spots." },
  patronus_woolly_mammoth: { label: "Woolly mammoth", blurb: "Ancient endurance — memory older than fear." },
  patronus_serpent: { label: "Serpent", blurb: "Patient coils — transformation shed skin by skin." },
  patronus_dolphin: { label: "Dolphin", blurb: "Joyful intelligence — you breathe between worlds." },
  patronus_badger: { label: "Badger", blurb: "Dig in, hold ground — softness above, stubbornness below." },
  patronus_owl: { label: "Owl", blurb: "Messages through darkness — wisdom that keeps hours others miss." },
  patronus_orca: { label: "Orca", blurb: "Strategic hunters — family, sea, and coordinated power." },
  patronus_panda: { label: "Panda", blurb: "Gentle giant energy — calm until the bamboo runs out." },
  patronus_black_and_white_cat: { label: "Black and white cat", blurb: "Balance in fur — curiosity with a neat line down the middle." },
};

/** Garrick Ollivander’s known wand woods (Wizarding World). */
export const WAND_WOODS = {
  wood_acacia: { label: "Acacia", blurb: "Subtle, tricky — best for wizards with finesse; not for the heavy-handed." },
  wood_alder: { label: "Alder", blurb: "Suits helpers and travellers; blossoms for the unselfish." },
  wood_apple: { label: "Apple", blurb: "Loves living magic; reputed to mix poorly with the darkest arts." },
  wood_ash: { label: "Ash", blurb: "Loyal to one master — stubborn, noble, hard to win and harder to steal." },
  wood_aspen: { label: "Aspen", blurb: "For duelists with steady nerve — revolutions and revellers." },
  wood_beech: { label: "Beech", blurb: "Tolerant, wise — if narrow-minded, the wand withers." },
  wood_blackthorn: { label: "Blackthorn", blurb: "Warrior’s wood — needs a fighter’s spirit to truly wake." },
  wood_black_walnut: { label: "Black walnut", blurb: "Insight and inner certainty — cannot abide self-deception." },
  wood_cedar: { label: "Cedar", blurb: "For the stealer of hearts — feared by Seers, loved by the brave." },
  wood_cherry: { label: "Cherry", blurb: "Deadly in the right hands — power married to control." },
  wood_chestnut: { label: "Chestnut", blurb: "Curious, practised, best with a beast-tamer or Herbologist." },
  wood_cypress: { label: "Cypress", blurb: "Associated with nobility through loss — unafraid of endings." },
  wood_dogwood: { label: "Dogwood", blurb: "Playful, clever, hungry for fun — never ordinary." },
  wood_ebony: { label: "Ebony", blurb: "For the individualist — often non-conformists and fierce duellists." },
  wood_elder: { label: "Elder", blurb: "Rarest, fateful — immense power and a traveller’s soul." },
  wood_elm: { label: "Elm", blurb: "Prefers magic with presence — not the mediocre or timid." },
  wood_english_oak: { label: "English oak", blurb: "Strength, loyalty, and leaders who protect their own." },
  wood_fir: { label: "Fir", blurb: "Survivors’ wood — resilient, formidable, a little intimidating." },
  wood_hawthorn: { label: "Hawthorn", blurb: "Complex, contradictory — healing and harm in one branch." },
  wood_hazel: { label: "Hazel", blurb: "Sensitive to its owner’s emotional state — reflects inner weather." },
  wood_holly: { label: "Holly", blurb: "Traditional protection — suited to perilous quests." },
  wood_hornbeam: { label: "Hornbeam", blurb: "For the single-minded, the focused, the occasionally obsessive." },
  wood_larch: { label: "Larch", blurb: "Bold, confident, and unexpectedly good-humoured." },
  wood_laurel: { label: "Laurel", blurb: "Cannot perform dishonourable acts — tries to leap from unworthy hands." },
  wood_maple: { label: "Maple", blurb: "For explorers and innovators — bored by the predictable." },
  wood_pear: { label: "Pear", blurb: "Golden, warm — beloved of the generous and popular." },
  wood_pine: { label: "Pine", blurb: "Independent, solitary — often artistic and intriguing." },
  wood_poplar: { label: "Poplar", blurb: "For clear moral vision — strong, even, dependable." },
  wood_red_oak: { label: "Red oak", blurb: "For swift, reactive magic — hot-blooded and loyal." },
  wood_redwood: { label: "Redwood", blurb: "For those who find luck — lasting, towering fortune." },
  wood_rowan: { label: "Rowan", blurb: "Defensive, pure reputation — a shield against Dark Arts." },
  wood_silver_lime: { label: "Silver lime", blurb: "Prized by legilimens and seers — strange, visionary gifts." },
  wood_spruce: { label: "Spruce", blurb: "For the bold moralist — blunt, sure, occasionally tactless." },
  wood_sycamore: { label: "Sycamore", blurb: "Restless, questing — if bored, the wand may wither." },
  wood_vine: { label: "Vine", blurb: "For deep visionaries, prophets, and those with larger destinies." },
  wood_walnut: { label: "Walnut", blurb: "For the ingenious — adapts fast, may turn if its wielder cannot." },
  wood_willow: { label: "Willow", blurb: "Healing instincts — often chooses those with deepest insecurities." },
  wood_yew: { label: "Yew", blurb: "Death and eternity — fearsome in duelling, rare and grave." },
};

/** Cores explicitly mentioned across HP books, Ilvermorny lore & extended materials. */
export const WAND_CORES = {
  core_phoenix_feather: { label: "Phoenix feather", blurb: "Acts of its own accord — widest range, hardest to tame." },
  core_unicorn_hair: { label: "Unicorn hair", blurb: "Steady, faithful — consistent magic, hardest to turn Dark." },
  core_dragon_heartstring: { label: "Dragon heartstring", blurb: "Powerful, quick-learning — can change allegiance if won." },
  core_thestral_tail_hair: { label: "Thestral tail hair", blurb: "Master of death’s sight — fateful, not common trade." },
  core_veela_hair: { label: "Veela hair", blurb: "Temperamental, volatile — dazzling when it agrees with you." },
  core_thunderbird_tail_feather: { label: "Thunderbird tail feather", blurb: "Sensitive to danger — powerful Transfiguration ally." },
  core_horned_serpent_horn: { label: "Horned Serpent horn", blurb: "Jewel-bright core — favours powerful, penetrating magic." },
  core_white_river_monster_spine: { label: "White River Monster spine", blurb: "Rare North-American core — formidable, sought by wandmakers." },
  core_basilisk_horn: { label: "Basilisk horn", blurb: "Dark, singular — Parseltongue wakes what should sleep." },
};

export const HOUSE_KEYS = /** @type {const} */ (["gryffindor", "slytherin", "ravenclaw", "hufflepuff"]);
export const CLASS_KEYS = Object.keys(CLASSES);
export const SPELL_KEYS = Object.keys(SPELLS);
export const PATRONUS_KEYS = Object.keys(PATRONUSES);
export const WOOD_KEYS = Object.keys(WAND_WOODS);
export const CORE_KEYS = Object.keys(WAND_CORES);
